import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TanstckProvider from './_providers/TanStack.provider';
import SonnerProvider from './_providers/Sonner.provider';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TanstckProvider>
                    <SonnerProvider>
                        {children}
                    </SonnerProvider>
                </TanstckProvider>


            </body>
        </html>
    );
};

export default RootLayout;