import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import RootContextProvider from './_contexts';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppRouterCacheProvider>


                    <RootContextProvider>

                        {children}
                    </RootContextProvider>


                </AppRouterCacheProvider>




            </body>
        </html>
    );
};

export default RootLayout;